language: swift

osx_image: xcode10.0

# Ensure that fastlane is at the latest version
before_install:
# - bundle update
# - brew update && brew install swiftlint

# Let fastlane set up the other dependency managers
before_script:
- bundle exec fastlane kit_carthage_build

# Separate fastlane lanes so that they can be individually
# tested one by one during development
script:
- bundle exec fastlane kit_swift_lint
- bundle exec fastlane kit_test
